### ISSUE TITLE
Doesn't Generate Anything

### ISSUE THREAD

**Issue by 44cK3r** [CK1412/image_generator#58]
Doesn't Generate Anything At All On Android Please Fix As I'm Already In Love With It Even Though It Doesn't Work Thank You Lots Of Love Keep It Up And Stay Positive

**Comment by CK1412** [comment]
Have you added your API KEY value? 
My available APK link doesn't work because it doesn't have an API_KEY

**Comment by 44cK3r** [comment]
How on earth do I do that???

**Comment by CK1412** [comment]
you create API KEY from account of [Open AI](https://platform.openai.com/docs/overview) and follow by step by step in Readme of this project to add key

**Comment by 44cK3r** [comment]
Ok thank you so very much
